services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: next-app
    container_name: app
    ports:
      - '3000:3000'
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./src:/app
    command: bash -c "npm run dev"

volumes:
  node_modules: